<?php
$z[0]=Array("flink","  [field:link /]  ",177,255);
$z[0][4]=array();
$z[0][4]['titlelen']="20";
$z[0][4]['row']="20";
$z[0][4]['type']="text";
$z[1]=Array("global","",382,408);
$z[1][4]=array();
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",409,433);
$z[2][4]=array();
$z[2][4]['name']="cfg_beian";
$z[3]=Array("type","\r\n            <li><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n            ",598,718);
$z[3][4]=array();
$z[3][4]['typeid']="1";
$z[4]=Array("type","\r\n            <li><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n            ",748,868);
$z[4][4]=array();
$z[4][4]['typeid']="2";
$z[5]=Array("type","\r\n            <li><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n            ",897,1017);
$z[5][4]=array();
$z[5][4]['typeid']="7";
$z[6]=Array("global","",1298,1319);
$z[6][4]=array();
$z[6][4]['name']="cfg_dh";
$z[7]=Array("global","",1402,1423);
$z[7][4]=array();
$z[7][4]['name']="cfg_sj";
$z[8]=Array("type"," <a href=\"[field:typelink/]\"><span class=\"icon-user\"></span>联系</a>",1498,1602);
$z[8][4]=array();
$z[8][4]['typeid']="7";

?>