<?php
$z[0]=Array("global","",194,220);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","(@me==\"\")? @me=\" class='current' \":@me=\"\";",460,552);
$z[1][4]=array();
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channelartlist","\r\n              <li class='{dede:field.currentstyle/}'><a class=\"first-level\" href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a></li>\r\n              ",623,870);
$z[2][4]=array();
$z[2][4]['typeid']="1,2";
$z[2][4]['currentstyle']="current";
$z[3]=Array("channelartlist","\r\n              <li class='{dede:field.currentstyle/}'><a class=\"first-level four\" href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a></li>\r\n              ",886,1138);
$z[3][4]=array();
$z[3][4]['typeid']="3,3";
$z[3][4]['currentstyle']="current";
$z[4]=Array("channelartlist","\r\n              <li class='{dede:field.currentstyle/}'><a class=\"first-level\" href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a></li>\r\n              ",1154,1405);
$z[4][4]=array();
$z[4][4]['typeid']="4,5,6,7";
$z[4][4]['currentstyle']="current";

?>